require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'ReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ReactNativeExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.6.10' })
  post_install do |installer|
    flipper_post_install(installer)
  end
  pod 'RCTCordova', :path => '../node_modules/@remobile/react-native-cordova/ios'
  pod 'RCTIndoorAtlas', :path => '../node_modules/react-native-indooratlas/src/ios'
end
